import { faCar, faMotorcycle, faHome, faShip, faUserInjured, faHeart, faBuilding, faStore, faUmbrellaBeach, faHandHoldingUsd, faHandshake, faHeartbeat, faUserMd, faPeopleCarry, faPaw, faRestroom, faMoneyBillAlt, faHandPeace, faShoppingCart, faAddressBook, faHourglassEnd, faUserPlus, faIdCard, faStethoscope } from '@fortawesome/free-solid-svg-icons';


export const listProducts = [
  "auto",
  "moto",
  "hogar",
  // "embarcaciones",
  "ap",
  // "vida",
  // "incediorcalquiler",
  // "caucionalquiler",
  // "retiro",
  // "banco",
  // "vidasocietario",
  // "salud",
  // "medprepagacol",
  // "art",
  // "mascotas",
  // "domestico",
  // "invesion",
  // "freestyle",
  // "bancodelsolrrhh",
  // "prepagarrhh",
  // "artrrhh",
  // "obligacionespatron",

  "grupomotoauto",
  "avipar",
  // "gruporedint",
  // "recibosueldo",
  // "retirocolectivorrhh",
  // "saludcolectivorrhh",
  // "vidacolectivorrhh"  
];
export const infoProducts = {
  auto: {
    title: "Automotores y Flotas",
    img: faCar,
    path: "automotores-flotas",
    client: 'Persona',
  },
  moto: {
    title: "Motos",
    img: faMotorcycle,
    path: "motos",
    client: 'Persona',
  },
  hogar: {
    title: "Hogar",
    img: faHome,
    path: "hogar",
    client: 'Persona',
  },
  embarcaciones: {
    title: "Embarcaciones",
    img: faShip,
    path: "embarcaciones",
    client: 'Persona',
  },
  ap: {
    title: "Accidentes Personales",
    img: faUserInjured,
    path: "accidentes-personales",
    client: 'Persona',
  },
  vida: {
    title: "Seguro de Vida",
    img: faHeart,
    path: "vida",
    client: 'Persona',
  },
  incediorcalquiler: {
    title: "Incendio y RC Alquileres",
    img: faBuilding,
    path: "incendio-rc-alquileres",
    client: 'Persona',
  },
  caucionalquiler: {
    title: "Caución Alquileres",
    img: faStore,
    path: "caucion-alquileres",
    client: 'Persona',
  },
  retiro: {
    title: "Retiro",
    img: faUmbrellaBeach,
    path: "retiro",
    client: 'Persona',
  },
  banco: {
    title: "Banco Del Sol",
    img: faHandHoldingUsd,
    path: "banco-del-sol",
    client: 'Persona',
  },
  vidasocietario: {
    title: "Seguro de Vida Societario",
    img: faHandshake,
    path: "seguro-vida-societario",
    client: 'Persona',
  },
  salud: {
    title: "Seguro de Salud",
    img: faHeartbeat,
    path: "salud",
    client: 'Persona',
  },
  medprepagacol: {
    title: "Medicina Prepaga Colectivo",
    img: faUserMd,
    path: "medicina-prepaga-colectivo",
    client: 'Persona',
  },
  art: {
    title: "ART",
    img: faPeopleCarry,
    path: "art",
    client: 'Persona',
  },
  mascotas: {
    title: "Mascotas",
    img: faPaw,
    path: "mascotas",
    client: 'Persona',
  },
  domestico: {
    title: "Personal Doméstico",
    img: faRestroom,
    path: "domestico",
    client: 'Persona',
  },
  invesion: {
    title: "Prestamos proyectos Inversión",
    img: faMoneyBillAlt,
    path: "inversion",
    client: 'Persona',
  },
  freestyle: {
    title: "Seguros FreeStyle",
    img: faHandPeace,
    path: "freeStyle",
    client: 'Persona',
  },
  //! a partir de aqui empresas
  "bancodelsolrrhh": {
    title: "Banco Del Sol",
    img: faHandHoldingUsd,
    path: "banco-del-sol-rrhh",
    client: 'Empresa',
  },
  prepagarrhh: {
    title: "Medicina Prepaga Colectivo",
    img: faUserMd,
    path: "medicina-prepaga-colectivo-rrhh",
    client: 'Empresa',
  },
  artrrhh: {
    title: "ART",
    img: faPeopleCarry,
    path: "art-rrhh",
    client: 'Empresa',
  },
  obligacionespatron: {
    title: "Seguros de Obligaciones Patronales",
    img: faIdCard,
    path: "seguros-de-obligaciones-patronales",
    client: 'Empresa',
  },
  avipar: {
    title: "Avipar",
    img: faMotorcycle,
    path: "avipar",
    client: 'Empresa',
  },
  grupomotoauto: {
    title: "Cotización Grupal Motos y Autos",
    img: faCar,
    path: "grupal-motos-y-autos",
    client: 'Empresa',
  },
  gruporedint: {
    title: "Cotización Grupal Red del Interior",
    img: faShoppingCart,
    path: "grupal-red-del-interior",
    client: 'Empresa',
  },
  recibosueldo: {
    title: "Recibo de Sueldo Digital",
    img: faAddressBook,
    path: "recibo-de-sueldo-digital",
    client: 'Empresa',
  },
  retirocolectivorrhh: {
    title: "Seguro de Retiro Colectivo",
    img: faHourglassEnd,
    path: "seguro-de-retiro-colectivo-rrhh",
    client: 'Empresa',
  },
  saludcolectivorrhh: {
    title: "Seguro de Salud Colectivo",
    img: faStethoscope,
    path: "salud-colectivo-rrhh",
    client: 'Empresa',
  },
  vidacolectivorrhh: {
    title: "Seguro de Vida Colectivo",
    img: faUserPlus,
    path: "vida-colectivo-rrhh",
    client: 'Empresa',
  },
}



